# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.9.0.schema.json
PackageIdentifier: nextestudios.ControlFS
PackageVersion: 0.14.0-alpha.1
InstallerType: inno
Scope: user
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
MinimumOSVersion: 10.0.19041.0
ReleaseDate: 2026-09-30
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/nextestudios/ControlFS/releases/download/v0.14.0-alpha.1/ControlFS-Setup-x64.exe
  InstallerSha256: 18EDF5CEDE38C342FFCD701589A1EE948FC06EED63810AFA62ED435FF1870E51
ManifestType: installer
ManifestVersion: 1.9.0
